apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sparenaproxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsparenaproxy
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/sparenaproxy/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://sparenaproxy.nais.preprod.local"
  webproxy: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: SPARENAPROXY_DB_URL
      value: jdbc:postgresql://b27dbvl016.preprod.local:5432/sparenaproxy
    - name: SMREGISTER_SCOPE
      value: "api://dev-fss.teamsykmelding.syfosmregister/.default"
    - name: MQ_HOST_NAME
      value: b27apvl176.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC02
    - name: MQ_CHANNEL_NAME
      value: Q1_SPARENAPROXY
    - name: MQ_ARENA_QUEUE_NAME
      value: QA.Q1_ARENA.MELD_FRA_SPARENAPROXY
    - name: MQ_KVITTERING_QUEUE_NAME
      value: QA.Q1_SPARENAPROXY.MELD_KVITT_FRA_ARENA
    - name: MQ_KVITTERING_BQ_QUEUE_NAME
      value: QA.Q1_SPARENAPROXY.MELD_KVITT_FRA_ARENA_BOQ
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: KAFKA_CLIENT_ID
      value: "sparenaproxy"
    - name: SPOKELSE_SCOPE
      value: "api://dev-fss.tbd.spokelse/.default"