apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sparenaproxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  gcp:
    sqlInstances:
      - name: sparenaproxy-db-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: sparenaproxy
            envVarPrefix: NAIS_DATABASE
            users:
              - name: sparenajob
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 400Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: flex-syketilfelle
          namespace: flex
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: b27apvl220.preprod.local
          ports:
            - port: 1413
  envFrom:
    - secret: srvsparenaproxy-secrets
    - secret: sparenaproxy-keystore-pwd
  filesFrom:
    - mountPath: /var/run/keystore
      secret: sparenaproxy-keystore
  secureLogs:
    enabled: true
  env:
    - name: SMREGISTER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregister/.default
    - name: MQ_HOST_NAME
      value: b27apvl220.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS02
    - name: MQ_CHANNEL_NAME
      value: Q1_SPARENAPROXY
    - name: MQ_ARENA_QUEUE_NAME
      value: QA.Q1_ARENA.MELD_FRA_SPARENAPROXY
    - name: MQ_KVITTERING_QUEUE_NAME
      value: QA.Q1_SPARENAPROXY.MELD_KVITT_FRA_ARENA
    - name: MQ_KVITTERING_BQ_QUEUE_NAME
      value: QA.Q1_SPARENAPROXY.MELD_KVITT_FRA_ARENA_BOQ
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: KAFKA_CLIENT_ID
      value: "sparenaproxy"
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://dev-gcp.flex.flex-syketilfelle/.default
    - name: MQ_KEYSTORE_PATH
      value: /var/run/keystore/sparenaproxy-keystore.jks
